export const PROJECT_ACTION = 'PROJECT_ACTION';
export const ANOTHER_PROJECT_ACTION = 'ANOTHER_PROJECT_ACTION';
export const ABOUT_ACTION = 'ABOUT_ACTION';
export const ANOTHER_ABOUT_ACTION = 'ANOTHER_ABOUT_ACTION';
